# Generated by Django 3.1.1 on 2020-09-27 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64)),
                ('user_surname', models.CharField(max_length=64)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_keyword', models.CharField(max_length=64)),
                ('user_ccdata', models.CharField(max_length=64)),
                ('user_hashPassword', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=64)),
                ('doctor_type', models.CharField(max_length=64)),
                ('clinic_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=64)),
                ('picture', models.ImageField(upload_to='profiles')),
                ('clientUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CrudAPI.clientuser')),
            ],
        ),
        migrations.CreateModel(
            name='HealthAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('address', models.TextField()),
                ('status', models.TextField()),
                ('price', models.IntegerField()),
                ('clinic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CrudAPI.clinic')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CrudAPI.clientuser')),
            ],
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('info', models.BinaryField()),
                ('status', models.CharField(max_length=64)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_sent', to='CrudAPI.clientuser')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_received', to='CrudAPI.clientuser')),
            ],
        ),
    ]
