# Generated by Django 3.1.1 on 2020-10-21 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CrudAPI', '0002_auto_20200927_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_name', models.CharField(max_length=64)),
                ('analysis_franchise_name', models.CharField(max_length=64)),
                ('analysis_contents', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicsFranchise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('franchise_full_name', models.CharField(default='HOME', max_length=64)),
                ('franchise_addr', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('speciality', models.CharField(max_length=64)),
                ('clinics_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.RenameField(
            model_name='healthagreement',
            old_name='clinic_id',
            new_name='clinic',
        ),
        migrations.RemoveField(
            model_name='healthagreement',
            name='user_id',
        ),
        migrations.AddField(
            model_name='clinic',
            name='franchise_name',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthagreement',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
